### PR TITLE
Add Windows RT links

### PR DESCRIPTION
**Pull request by Ghabry**

### CODE REVIEW

**Comment by carstene1ns** [comment]
As the WinRT version is not going to be tested as much as the others, maybe this should go under contributed ports instead...?

**Comment by Ghabry** [comment]
I agree. Is not of general interest.

**Comment by Ghabry** [comment]
When do we delete GCW-Zero? :P

**Comment by fdelapena** [comment]
[Offtopic] iOS (Jailbreak) port could be added in the same form, too.

**Comment by Ghabry** [comment]
When we have a touch ui it would make sense ^^

**Comment by carstene1ns** [comment]
Do we wait until 0.4.1 or 0.5 to add it as a whole or should we fake a (tagged) 0.4 version for the download link?
Would also be possible to remove the first link for now and have it added after next tag.

**Comment by Ghabry** [comment]
I planned to fake this. Nobody will notice ;)

**Comment by carstene1ns** [comment]
kk, then let's merge this after the file is in place.

**Pull request merged**
