### PR TITLE
Add 3ds links + add explanations to CI builds

### PR DESCRIPTION
**Pull request by Ghabry**
I removed the "Note:" prefixes because I don't think you really need this and copy-pasted most of the descriptions also to the CI builds.

The 3DS build links the 3dsx and the CIA and I credited Rinne with a link to his website. (I'm not linking the ELF because it's not of general interest, Rinne has a tutorial in his forum where he explains the purpose of the ELF)

Showcase:
https://easy-rpg.org/jenkins/job/website-pr/ws/output/player/downloads/index.html

### CODE REVIEW

**Comment by carstene1ns** [comment]
2 small issues:
- The sentence above the continuous builds is now superfluous and can be removed ("The notes from the release builds above also apply.")
- The front page needs an update in the cross-platform section (+edited logo)

**Comment by Ghabry** [comment]
I never saw that sentence :O

**Comment by Ghabry** [comment]
And here is a logo with a PSP just for convenience ;)

[logo_with_psp.zip](https://github.com/EasyRPG/easy-rpg.org/files/244355/logo_with_psp.zip)

logo_with_psp

**Comment by Ghabry** [comment]
Is the logo fine or do you have a SVG I shall edit?

**Comment by fdelapena** [comment]
No, there is no SVG, I could gather all vector logos again to have a better way, but your edition LGTM.

**Comment by carstene1ns** [comment]
The image is 16 pixels higher than before. This needs an adjustment in [easyrpg.scss](https://github.com/EasyRPG/easy-rpg.org/blob/master/content/css/easyrpg.scss#L215).
Current value is `height (130px) + padding (15px) = 145px`. A new value of `160px` should be ok.

**Comment by Ghabry** [comment]
Imo the gap for 160 px was very thin between heading + picture, I used 165px.

**Comment by Ghabry** [comment]
Meh I had this nice prepared logo with a PSP icon and now I need one with Vita >.>

**Pull request merged**
